AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Receive and parse emails sent to SES email domain.
Parameters:
  EmailAddress:
    Type: String
  ReceiveEmailBucket:
    Type: String

Resources:
  ReceiveEmail:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: ReceiveEmail
      Handler: receive_email.lambda_handler
      Runtime: python3.7
      Timeout: 120
      Policies:
      - SNSPublishMessagePolicy:
          TopicName: !GetAtt ReceiveEmailTopic.TopicName
      - S3ReadPolicy:
          BucketName: !Ref ReceiveEmailBucket
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref ReceiveEmailTopic
      Events:
        ReceiveEmailEvent:
          Type: S3
          Properties:
            Bucket: !Ref ReceiveEmailBucket
            Events: s3:ObjectCreated:*

  ReceiveEmailTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Protocol: email
        Endpoint: !Ref EmailAddress