AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Receive and parse emails sent to SES email domain.
Parameters:
  EmailAddress:
    Type: String
  EmailDomain:
    Type: String
  EmailBucketName:
    Type: String

Resources:
  # Lambda function that is triggered when a new file is created in an S3 bucket
  # Function parses the file contents and send the content using SNS (eventually SES)
  ReceiveEmail:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: ReceiveEmail
      Handler: receive_email.lambda_handler
      Runtime: python3.7
      Timeout: 120
      Policies:
      - SESCrudPolicy:
          IdentityName: !Ref EmailDomain
      # - SNSPublishMessagePolicy:
      #     TopicName: !GetAtt ReceiveEmailTopic.TopicName
      - S3ReadPolicy:
          BucketName: !Ref EmailBucketName
      Environment:
        Variables:
          # SNS_TOPIC_ARN: !Ref ReceiveEmailTopic
          EMAIL_ADDRESS: !Ref EmailAddress
          EMAIL_DOMAIN: !Ref EmailDomain
      Events:
        ReceiveEmailEvent:
          Type: S3
          Properties:
            Bucket: !Ref ReceiveEmailBucket
            Events: s3:ObjectCreated:*

  # SNS topic where notifications are published and the parsed email content is sent
  # ReceiveEmailTopic:
  #   Type: AWS::SNS::Topic
  #   Properties:
  #     Subscription:
  #     - Protocol: email
  #       Endpoint: !Ref EmailAddress
  
  # Bucket where files are created whenever a new email message is sent to the domain name
  ReceiveEmailBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref EmailBucketName
  
  # S3 policy that enables SES to put incoming emails into the bucket as files
  ReceiveEmailBucketSESPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:  
      Bucket:  
        Ref: ReceiveEmailBucket 
      PolicyDocument:  
        Version: 2012-10-17
        Statement:  
        - Sid: ReceiveEmailBucketSESPolicy
          Action: s3:PutObject
          Effect: Allow
          Resource: !Sub arn:aws:s3:::${EmailBucketName}/*
          Principal: 
            Service: ses.amazonaws.com 