AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Receive and parse emails sent to SES email domain.
Parameters:
  EmailAddress:
    Type: String

Resources:
  ReceiveEmail:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: ReceiveEmail
      Handler: receive_email.lambda_handler
      Runtime: python3.7
      Timeout: 120
      Policies:
      - SNSPublishMessagePolicy:
          TopicName: !GetAtt ReceiveEmailTopic.TopicName
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref ReceiveEmailTopic

  ReceiveEmailTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Protocol: email
        Endpoint: !Ref EmailAddress